### ISSUE TITLE
NPE with maven-publish

### ISSUE THREAD

**Issue by ultrah** [layerhq/gradle-git-repo-plugin#8]
When I use this plugin with maven-publish, I get an error:

 gradle -Porg=foo -Prepo=bar :app:publish --stacktrace
Parallel execution is an incubating feature.
:app:cloneRepo
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
:app:generatePomFileForSdkPublication
:app:publishSdkPublicationToMaven2Repository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishSdkPublicationToMaven2Repository'.
> Failed to publish publication 'sdk' to repository 'maven2'
   > java.lang.NullPointerException (no error message)

Stacktrace:

        Caused by: org.gradle.api.artifacts.PublishException: Failed to publish publication 'sdk' to repository 'maven2'
                at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:39)
                at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.doPublish(PublishToMavenRepository.java:142)
                at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.publish(PublishToMavenRepository.java:133)
                at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
                at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
                at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
                ... 54 more
        Caused by: java.lang.NullPointerException
                at org.gradle.api.publish.maven.internal.publisher.MavenRemoteRepositoryFactory.create(MavenRemoteRepositoryFactory.java:35)
                at org.gradle.api.publish.maven.internal.publisher.AntTaskBackedMavenPublisher.addRepository(AntTaskBackedMavenPublisher.java:46)
                at org.gradle.api.publish.maven.internal.publisher.AntTaskBackedMavenPublisher.postConfigure(AntTaskBackedMavenPublisher.java:36)
                at org.gradle.api.publish.maven.internal.publisher.AntTaskBackedMavenPublisher.postConfigure(AntTaskBackedMavenPublisher.java:30)
                at org.gradle.api.publish.maven.internal.publisher.AbstractAntTaskBackedMavenPublisher.publish(AbstractAntTaskBackedMavenPublisher.java:59)
                at org.gradle.api.publish.maven.internal.publisher.StaticLockingMavenPublisher.publish(StaticLockingMavenPublisher.java:38)
                at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:48)
                at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$2.publish(PublishToMavenRepository.java:148)
                at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:37)
                ... 64 more

when I use the old maven plugin it works fine, but I need to use the maven-publish

any idea?

**Comment by drapp** [comment]
what does your `publishing` block look like? Also, what is this `publishSdkPublicationToMaven2Repository` Is that part of a plugin, or something custom?

**Comment by ultrah** [comment]
I assume that it's part of the maven-publish plugin

    publishing {
        publications {
            sdk(MavenPublication) {
                artifactId libName
                artifact "${project.buildDir}/outputs/aar/${libName}-${project.version}.aar"

                //The publication doesn't know about our dependencies, so we have to manually add them to the pom
                pom.withXml {
                    // for dependencies and exclusions
                    def dependenciesNode = asNode().appendNode('dependencies')
                    configurations.compile.allDependencies.each { ModuleDependency dp ->
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', dp.group)
                        dependencyNode.appendNode('artifactId', dp.name)
                        dependencyNode.appendNode('version', dp.version)

                        // for exclusions
                        if (dp.excludeRules.size() > 0) {
                            def exclusions = dependencyNode.appendNode('exclusions')
                            dp.excludeRules.each { ExcludeRule ex ->
                                def exclusion = exclusions.appendNode('exclusion')
                                exclusion.appendNode('groupId', ex.group)
                                exclusion.appendNode('artifactId', ex.module)
                            }
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                repositories {
                    maven {
                        url "file://${System.env.HOME}/.gitRepos/${property("org")}/${property("repo")}/releases"
                    }
                }
            }
        }
    }

**Comment by ultrah** [comment]
Any clue? :)
